-- ============================================================
--  CUK-Loadout  |  config.lua
-- ============================================================

Config = {}

-- Ammo amount given per weapon
Config.AmmoCount = 9999

-- Refill stamina/oxygen every X milliseconds
Config.RefillInterval = 5000

-- All GTA V weapons
Config.Weapons = {
    -- Melee
    'WEAPON_DAGGER',
    'WEAPON_BAT',
    'WEAPON_BOTTLE',
    'WEAPON_CROWBAR',
    'WEAPON_FLASHLIGHT',
    'WEAPON_GOLFCLUB',
    'WEAPON_HAMMER',
    'WEAPON_HATCHET',
    'WEAPON_KNUCKLE',
    'WEAPON_KNIFE',
    'WEAPON_MACHETE',
    'WEAPON_SWITCHBLADE',
    'WEAPON_NIGHTSTICK',
    'WEAPON_WRENCH',
    'WEAPON_BATTLEAXE',
    'WEAPON_POOLCUE',
    'WEAPON_STONE_HATCHET',

    -- Pistols
    'WEAPON_PISTOL',
    'WEAPON_PISTOL_MK2',
    'WEAPON_COMBATPISTOL',
    'WEAPON_APPISTOL',
    'WEAPON_STUNGUN',
    'WEAPON_PISTOL50',
    'WEAPON_SNSPISTOL',
    'WEAPON_SNSPISTOL_MK2',
    'WEAPON_HEAVYPISTOL',
    'WEAPON_VINTAGEPISTOL',
    'WEAPON_FLAREGUN',
    'WEAPON_MARKSMANPISTOL',
    'WEAPON_REVOLVER',
    'WEAPON_REVOLVER_MK2',
    'WEAPON_DOUBLEACTION',
    'WEAPON_RAYPISTOL',
    'WEAPON_CERAMICPISTOL',
    'WEAPON_NAVYREVOLVER',
    'WEAPON_GADGETPISTOL',

    -- Shotguns
    'WEAPON_PUMPSHOTGUN',
    'WEAPON_PUMPSHOTGUN_MK2',
    'WEAPON_SAWNOFFSHOTGUN',
    'WEAPON_ASSAULTSHOTGUN',
    'WEAPON_BULLPUPSHOTGUN',
    'WEAPON_MUSKET',
    'WEAPON_HEAVYSHOTGUN',
    'WEAPON_DBSHOTGUN',
    'WEAPON_AUTOSHOTGUN',
    'WEAPON_COMBATSHOTGUN',

    -- SMGs
    'WEAPON_MICROSMG',
    'WEAPON_SMG',
    'WEAPON_SMG_MK2',
    'WEAPON_ASSAULTSMG',
    'WEAPON_COMBATPDW',
    'WEAPON_MACHINEPISTOL',
    'WEAPON_MINISMG',
    'WEAPON_RAYCARBINE',

    -- Assault Rifles
    'WEAPON_ASSAULTRIFLE',
    'WEAPON_ASSAULTRIFLE_MK2',
    'WEAPON_CARBINERIFLE',
    'WEAPON_CARBINERIFLE_MK2',
    'WEAPON_ADVANCEDRIFLE',
    'WEAPON_SPECIALCARBINE',
    'WEAPON_SPECIALCARBINE_MK2',
    'WEAPON_BULLPUPRIFLE',
    'WEAPON_BULLPUPRIFLE_MK2',
    'WEAPON_COMPACTRIFLE',
    'WEAPON_MILITARYRIFLE',
    'WEAPON_HEAVYRIFLE',
    'WEAPON_TACTICALRIFLE',

    -- Light Machine Guns
    'WEAPON_MG',
    'WEAPON_COMBATMG',
    'WEAPON_COMBATMG_MK2',
    'WEAPON_GUSENBERG',

    -- Sniper Rifles
    'WEAPON_SNIPERRIFLE',
    'WEAPON_HEAVYSNIPER',
    'WEAPON_HEAVYSNIPER_MK2',
    'WEAPON_MARKSMANRIFLE',
    'WEAPON_MARKSMANRIFLE_MK2',

    -- Heavy
    'WEAPON_RPG',
    'WEAPON_GRENADELAUNCHER',
    'WEAPON_GRENADELAUNCHER_SMOKE',
    'WEAPON_MINIGUN',
    'WEAPON_FIREWORK',
    'WEAPON_RAILGUN',
    'WEAPON_HOMINGLAUNCHER',
    'WEAPON_COMPACTLAUNCHER',
    'WEAPON_RAYMINIGUN',

    -- Throwables
    'WEAPON_GRENADE',
    'WEAPON_BZGAS',
    'WEAPON_MOLOTOV',
    'WEAPON_STICKYBOMB',
    'WEAPON_PROXMINE',
    'WEAPON_SNOWBALL',
    'WEAPON_PIPEBOMB',
    'WEAPON_BALL',
    'WEAPON_SMOKEGRENADE',
    'WEAPON_FLARE',

    -- Misc / Special
    'WEAPON_PETROLCAN',
    'WEAPON_HAZARDCAN',
    'WEAPON_FIREEXTINGUISHER',
    'WEAPON_PARACHUTE',
}
